name: .NET Build and Publish

on:
  push:
    branches: [ '**' ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '7.0.x'
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./BIOS9.ClickUp

    - name: Dump GitHub context
      run: |
         echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
         echo "Tag name from github.ref_name: ${{  github.ref_name }}"
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./BIOS9.ClickUp
      
    - name: Execute unit tests
      run: dotnet test --configuration Release --no-build
      working-directory: ./BIOS9.ClickUp

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
    - name: Create NuGet package
      run: dotnet pack --configuration Release --no-restore --output out
      working-directory: ./BIOS9.ClickUp

    - name: Dump GitHub context
      run: |
         ls
         pwd
         ls out
      working-directory: ./BIOS9.ClickUp
    
    - name: Push NuGet package
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
      working-directory: ./BIOS9.ClickUp

  
