name: .NET Build and Publish

on:
  push:
    branches: [ '**' ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: '7.0.x'

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./BIOS9.ClickUp

    - name: Get Build Version
      run: |
        Import-Module .\build\GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh
      
    - name: Build
      run: dotnet build --configuration Release -p:Version=$BUILD_VERSION --no-restore
      working-directory: ./BIOS9.ClickUp
      
    - name: Execute unit tests
      run: dotnet test --configuration Release --no-build
      working-directory: ./BIOS9.ClickUp

  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
    - name: Create NuGet package
      run: dotnet pack --configuration Release --no-restore --output out
    
    - name: Push NuGet package
      run: dotnet nuget push **/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}

  
