name: .NET Build and Publish

on:
  push:
    branches: [ '**' ]
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.3.0
      with:
        dotnet-version: '7.0.x'
    
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./BIOS9.ClickUp
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./BIOS9.ClickUp
      
    - name: Execute unit tests
      run: dotnet test --configuration Release --no-build
      working-directory: ./BIOS9.ClickUp

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'created'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get Build Version
      run: |
        Import-Module ./build/GetBuildVersion.psm1
        Write-Host $Env:GITHUB_REF
        $version = GetBuildVersion -VersionString $Env:GITHUB_REF
        echo "BUILD_VERSION=$version" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
      shell: pwsh

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.3.0
      with:
        dotnet-version: '7.0.x'
    
    - name: Create NuGet package
      run: dotnet pack ./BIOS9.ClickUp/BIOS9.ClickUp --configuration Release -p:Version=$BUILD_VERSION --output out
    
    - name: Push NuGet package
      run: dotnet nuget push ./out/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_API_KEY}}
